### ISSUE TITLE
Wallpaper can't change on Ubuntu 18.04 series

### ISSUE THREAD

**Issue by kelebek333** [KeithDHedger/Xfce-Theme-Manager#5]
Hi @KeithDHedger ,

First of all, thank you very much for the nice application you prepared.

Xfce-theme-manager's Wallpaper section can't change wallpaper. I think this issue is related to the reason I quoted below.

> gdk_screen_get_monitor_plug_name has been deprecated since version 3.22 and should not be used in newly-written code.
> 
> Use gdk_monitor_get_model() instead

https://developer.gnome.org/gdk3/stable/GdkScreen.html#gdk-screen-get-monitor-plug-name

On below link has a fix to xfdesktop for a similar situation. I thought it might be useful.

https://github.com/xfce-mirror/xfdesktop/commit/ee82a044329b7776ec0eae6e6124e78b3eb9bf37

Best regards

**Comment by KeithDHedger** [comment]
On Thu, 12 Dec 2019 13:15:59 -0800
Butterfly <notifications@github.com> wrote:

> Hi @KeithDHedger ,
> 
> First of all, thank you very much for the nice application you
> prepared.
> 
> Xfce-theme-manager's Wallpaper section can't change wallpaper. I
> think this issue is related to the reason I quoted below.
> 
> > gdk_screen_get_monitor_plug_name has been deprecated since version
> > 3.22 and should not be used in newly-written code.
> > 
> > Use gdk_monitor_get_model() instead  
> 
> https://developer.gnome.org/gdk3/stable/GdkScreen.html#gdk-screen-get-monitor-plug-name
> 
> Below is a fix for xfdesktop. 
> 
> https://github.com/xfce-mirror/xfdesktop/commit/ee82a044329b7776ec0eae6e6124e78b3eb9bf37
> 
> Best regards
> 

Hi

busy with xmas stuff give me a couple of days and i will sort it out,
thx for the bug report.

Keith

**Comment by KeithDHedger** [comment]
Fixed, tested on xubuntu 18.04 dual monitor.
