### ISSUE TITLE
Obseleted link for Xfce-Composite-Editor

### ISSUE THREAD

**Issue by kelebek333** [KeithDHedger/Xfce-Theme-Manager#6]
Hi @KeithDHedger ,

Xfce-Composite-Editor's link is obselete. Can you replace it with a link in use?

https://github.com/KeithDHedger/Xfce-Theme-Manager/blob/master/Xfce-Theme-Manager/src/callbacks.cpp#L1046

**Comment by KeithDHedger** [comment]
On Thu, 12 Dec 2019 13:31:59 -0800
Butterfly <notifications@github.com> wrote:

> Hi @KeithDHedger ,
> 
> Xfce-Composite-Editor's link is obselete. Can you replace it with a
> link in use?
> 
> https://github.com/KeithDHedger/Xfce-Theme-Manager/blob/master/Xfce-Theme-Manager/src/callbacks.cpp#L1046
> 

Hi

busy with xmas stuff give me a couple of days and i will sort it out,
thx for the bug report.

Keith

**Comment by KeithDHedger** [comment]
On Thu, 12 Dec 2019 13:31:59 -0800
Butterfly <notifications@github.com> wrote:

> Hi @KeithDHedger ,
> 
> Xfce-Composite-Editor's link is obselete. Can you replace it with a
> link in use?
> 
> https://github.com/KeithDHedger/Xfce-Theme-Manager/blob/master/Xfce-Theme-Manager/src/callbacks.cpp#L1046
> 

Fixed

Keith
